// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectAndExecuteCommands(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function UpdateLightDefender(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;
