// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectAndExecuteCommands(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function InstallLightDefender(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function LoadConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<Array<string>>;

export function UpdateLightDefender(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;
